[workspace]
resolver = "3"
members = [ "ponygame", "game" ]

[profile.release]
strip = true

[profile.dev.package."*"]
opt-level = 3

[profile.dev.package.ponygame]
opt-level = 0

[profile.dev.package.game]
opt-level = 0
